name: gnnattack
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly        # or replace with `pytorch-cuda=11.8` for GPU
  - pip
  - jupyter
  - matplotlib
  - seaborn
  - scikit-learn
  - pip:
      - torch-geometric
      - torch-scatter
      - torch-sparse
      - deeprobust
